from fastapi import FastAPI, HTTPException, Depends, Query, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import Optional, List
import os
import httpx

from .config import settings, SvmConfig
from .database import get_db, create_tables, S3Bucket
from .models import (
    StorageItem, StorageItemCreate, StorageItemUpdate,
    StorageItem, StorageItemCreate, StorageItemUpdate,
    StorageItemListResponse, ErrorResponse,
    S3UserCreate, S3User as S3UserSchema, S3UserCreateResponse, S3UserListResponse,
    SvmEnvironment, SvmEnvironmentsResponse, S3BucketCreate, S3BucketSchema, S3BucketListResponse,
)
from .crud import (
    get_storage_items, get_storage_item, create_storage_item,
    update_storage_item, delete_storage_item,
    get_s3_users, get_s3_user_by_username, create_s3_user, delete_s3_user,
    get_s3_buckets, create_s3_bucket, update_s3_bucket_uuid, delete_s3_bucket,
    mark_s3_bucket_deleting, mark_s3_bucket_deleted,
)
from .auth import get_current_user_optional, get_current_user_required, get_entra_auth_url, verify_entra_token, create_access_token
from datetime import datetime

# Create tables on startup
create_tables()

app = FastAPI(
    title="Storage Items API",
    description="A simple API for managing storage items with CRUD operations",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mount static files for frontend
frontend_dist_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "frontend", "build")
if os.path.exists(frontend_dist_path):
    app.mount("/static", StaticFiles(directory=frontend_dist_path, html=True), name="static")

@app.get("/", response_class=FileResponse)
async def serve_frontend():
    """Serve the React frontend"""
    frontend_index = os.path.join(frontend_dist_path, "index.html")
    if os.path.exists(frontend_index):
        return FileResponse(frontend_index)
    return {"message": "Storage API is running. Frontend not built yet."}

# Authentication endpoints
@app.get("/api/auth/status")
async def auth_status():
    """
    Returns current auth configuration.
    When ENABLE_ENTRA_AUTH=false, also issues a ready-made JWT for the dev user
    so the frontend can auto-login without any redirect flow.
    """
    if not settings.enable_entra_auth:
        token = create_access_token({"sub": settings.dev_user})
        return {
            "auth_enabled": False,
            "dev_user": settings.dev_user,
            "access_token": token,
        }
    return {"auth_enabled": True}

@app.get("/api/auth/login-url")
async def get_login_url(code_challenge: str = Query(..., description="PKCE code_challenge (S256) generated by the browser")):
    """
    Return the Entra ID authorisation URL.
    The browser must supply a PKCE code_challenge; the matching code_verifier
    is stored in sessionStorage and sent back at /api/auth/callback.
    """
    if not settings.enable_entra_auth:
        return {"enabled": False}

    auth_url = get_entra_auth_url(code_challenge)
    return {"enabled": True, "login_url": auth_url}

class AuthCallbackRequest(BaseModel):
    code: str
    code_verifier: str

@app.post("/api/auth/callback")
async def auth_callback(body: AuthCallbackRequest):
    """Handle Entra ID authentication callback"""
    try:
        result = verify_entra_token(body.code, body.code_verifier)
        # Create a JWT token for the authenticated user
        username = (result.get("id_token_claims") or {}).get("preferred_username") \
            or (result.get("account") or {}).get("username", "user")
        access_token = create_access_token({"sub": username})
        return {"access_token": access_token, "token_type": "bearer", "username": username}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

# Storage Items API endpoints
@app.get(
    "/api/storage-items", 
    response_model=StorageItemListResponse,
    responses={400: {"model": ErrorResponse}, 500: {"model": ErrorResponse}}
)
async def list_storage_items(
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    category: Optional[str] = Query(None),
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user_required())
):
    """List all storage items with optional pagination and filtering"""
    try:
        result = get_storage_items(db, owner_email=current_user, page=page, limit=limit, category=category)
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post(
    "/api/storage-items", 
    response_model=StorageItem,
    status_code=status.HTTP_201_CREATED,
    responses={400: {"model": ErrorResponse}, 409: {"model": ErrorResponse}, 500: {"model": ErrorResponse}}
)
async def create_new_storage_item(
    item: StorageItemCreate,
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user_required())
):
    """Create a new storage item"""
    try:
        return create_storage_item(db, item, owner_email=current_user)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get(
    "/api/storage-items/{item_id}", 
    response_model=StorageItem,
    responses={404: {"model": ErrorResponse}, 500: {"model": ErrorResponse}}
)
async def get_storage_item_by_id(
    item_id: str,
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user_required())
):
    """Get a storage item by ID"""
    item = get_storage_item(db, item_id, owner_email=current_user)
    if not item:
        raise HTTPException(status_code=404, detail="Storage item not found")
    return item

@app.put(
    "/api/storage-items/{item_id}", 
    response_model=StorageItem,
    responses={400: {"model": ErrorResponse}, 404: {"model": ErrorResponse}, 500: {"model": ErrorResponse}}
)
async def update_storage_item_by_id(
    item_id: str,
    item_update: StorageItemUpdate,
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user_required())
):
    """Update a storage item"""
    updated_item = update_storage_item(db, item_id, item_update, owner_email=current_user)
    if not updated_item:
        raise HTTPException(status_code=404, detail="Storage item not found")
    return updated_item

@app.delete(
    "/api/storage-items/{item_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    responses={404: {"model": ErrorResponse}, 500: {"model": ErrorResponse}}
)
async def delete_storage_item_by_id(
    item_id: str,
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user_required())
):
    """Delete a storage item"""
    deleted = delete_storage_item(db, item_id, owner_email=current_user)
    if not deleted:
        raise HTTPException(status_code=404, detail="Storage item not found")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_svm_or_404(environment: str) -> SvmConfig:
    """Resolve environment name to SvmConfig or raise 404."""
    configs = settings.get_svm_configs()
    cfg = configs.get(environment)
    if not cfg:
        raise HTTPException(
            status_code=404,
            detail=f"Environment '{environment}' is not configured.",
        )
    return cfg


def _netapp_headers() -> dict:
    return {"Content-Type": "application/json", "Accept": "application/json"}


async def log_request(request: httpx.Request):
    if settings.trace_mode:
        command = f"curl -X {request.method} -H " + " -H ".join(f"'{k}: {v}'" for k, v in request.headers.items()) + f" '{request.url}'"
        if request.content:
            try:
                command += f" -d '{request.content.decode()}'"
            except Exception:
                command += " -d '<binary>'"
        print(f"\\n[TRACE] Request: {command}")

async def log_response(response: httpx.Response):
    if settings.trace_mode:
        await response.aread()
        print(f"[TRACE] Response {response.status_code}: {response.text}\\n")

def get_netapp_client(cfg: SvmConfig, timeout: int = 30) -> httpx.AsyncClient:
    return httpx.AsyncClient(
        auth=(cfg.username, cfg.password),
        verify=settings.netapp_verify_ssl,
        timeout=timeout,
        event_hooks={'request': [log_request], 'response': [log_response]}
    )


# ---------------------------------------------------------------------------
# S3 Object Storage — Environment discovery
# ---------------------------------------------------------------------------

@app.get(
    "/api/s3/environments",
    response_model=SvmEnvironmentsResponse,
)
async def list_svm_environments(
    current_user=Depends(get_current_user_required()),
):
    """Return the list of configured SVM environment names (no credentials exposed)."""
    configs = settings.get_svm_configs()
    return SvmEnvironmentsResponse(
        environments=[SvmEnvironment(name=name) for name in configs]
    )


# ---------------------------------------------------------------------------
# S3 Object Storage — User Management endpoints
# ---------------------------------------------------------------------------

@app.get(
    "/api/s3/users",
    response_model=S3UserListResponse,
    responses={404: {"model": ErrorResponse}, 500: {"model": ErrorResponse}},
)
async def list_s3_users(
    environment: str = Query(..., description="SVM environment name, e.g. DEV/TEST"),
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_required()),
):
    """
    List all S3 users for the given environment stored in the local database.
    Also refreshes each user's details from NetApp so the UI always shows
    up-to-date access_key and key_expiry_time.
    """
    # Validate environment is configured
    cfg = _get_svm_or_404(environment)

    try:
        db_users = get_s3_users(db, owner_email=current_user, environment=environment)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    # Refresh details from NetApp for each user (best-effort — don't fail the
    # whole list if a single NetApp call fails).
    refreshed = []
    async with get_netapp_client(cfg, timeout=15) as client:
        for user in db_users:
            netapp_url = (
                f"{cfg.base_url}/protocols/s3/services"
                f"/{cfg.svm_uuid}/users/{user.username}"
            )
            try:
                resp = await client.get(netapp_url, headers=_netapp_headers())
                if resp.status_code == 200:
                    data = resp.json()
                    # NetApp may wrap the result in a records array
                    if "records" in data and data["records"]:
                        record = data["records"][0]
                    else:
                        record = data
                    # Update local fields if NetApp returned them
                    if record.get("access_key"):
                        user.access_key = record["access_key"]
                    if record.get("key_expiry_time") is not None:
                        user.key_expiry_time = record["key_expiry_time"]
            except Exception:
                pass  # Use locally stored data on failure
            refreshed.append(user)

    return {"data": refreshed}


@app.post(
    "/api/s3/users",
    response_model=S3UserCreateResponse,
    status_code=status.HTTP_201_CREATED,
    responses={
        400: {"model": ErrorResponse},
        404: {"model": ErrorResponse},
        409: {"model": ErrorResponse},
        502: {"model": ErrorResponse},
        500: {"model": ErrorResponse},
    },
)
async def create_new_s3_user(
    payload: S3UserCreate,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_required()),
):
    """
    Create a new S3 user on the NetApp SVM for the specified environment.

    NetApp POST /api/protocols/s3/services/{svm.uuid}/users
    Expected response (s3_user_post_patch_response):
      { "num_records": 1, "records": [{ "access_key": "...", "secret_key": "...",
                                        "name": "...", "key_expiry_time": "..." }] }

    The access_key (and optional key_expiry_time) are stored in the database.
    The secret_key is returned to the caller exactly once and never persisted.
    """
    cfg = _get_svm_or_404(payload.environment)

    # Check for duplicate username within this environment
    if get_s3_user_by_username(db, payload.environment, payload.username):
        raise HTTPException(
            status_code=409,
            detail=(
                f"S3 user '{payload.username}' already exists "
                f"in environment '{payload.environment}'."
            ),
        )

    netapp_url = (
        f"{cfg.base_url}/protocols/s3/services/{cfg.svm_uuid}/users"
    )
    netapp_body: dict = {"name": payload.username}
    if payload.comment:
        netapp_body["comment"] = payload.comment

    try:
        async with get_netapp_client(cfg, timeout=30) as client:
            response = await client.post(
                netapp_url,
                json=netapp_body,
                headers=_netapp_headers(),
            )
    except httpx.RequestError as exc:
        raise HTTPException(
            status_code=502,
            detail=f"Could not reach NetApp SVM API: {exc}",
        )

    if response.status_code not in (200, 201):
        raise HTTPException(
            status_code=502,
            detail=f"NetApp SVM API returned {response.status_code}: {response.text}",
        )

    try:
        netapp_data = response.json()
        # NetApp wraps results in a records array
        records = netapp_data.get("records", [])
        if not records:
            raise ValueError("Empty records array in NetApp response")
        record = records[0]
        access_key: str = record["access_key"]
        secret_key: str = record["secret_key"]
        key_expiry_time: Optional[str] = record.get("key_expiry_time")
    except (ValueError, KeyError) as exc:
        raise HTTPException(
            status_code=502,
            detail=f"Unexpected response from NetApp SVM API: {exc}",
        )

    # Persist user (without the secret)
    db_user = create_s3_user(
        db,
        owner_email=current_user,
        environment=payload.environment,
        username=payload.username,
        access_key=access_key,
        comment=payload.comment,
        key_expiry_time=key_expiry_time,
    )

    return S3UserCreateResponse(
        id=db_user.id,
        owner_email=db_user.owner_email,
        environment=db_user.environment,
        username=db_user.username,
        comment=db_user.comment,
        access_key=db_user.access_key,
        key_expiry_time=db_user.key_expiry_time,
        created_at=db_user.created_at,
        secret_key=secret_key,
    )

@app.delete("/api/s3/users/{username}", status_code=204)
async def delete_s3_user_route(
    username: str,
    environment: str = Query(...),
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_required()),
):
    """
    Delete an S3 user from the NetApp SVM and sync the local SQLite store.
    """
    # 1. Enforce ownership tracking natively in the DB query logic
    local_user = get_s3_user_by_username(db, environment, username)
    if not local_user or local_user.owner_email != current_user:
        raise HTTPException(status_code=404, detail="S3 user not found or you lack ownership permissions.")

    cfg = _get_svm_or_404(environment)
    netapp_url = f"{cfg.base_url}/protocols/s3/services/{cfg.svm_uuid}/users/{username}"

    # 2. Fire the network cancellation command to SVM
    try:
        async with get_netapp_client(cfg, timeout=30) as client:
            response = await client.delete(netapp_url, headers=_netapp_headers())
    except httpx.RequestError as exc:
        raise HTTPException(
            status_code=502,
            detail=f"Could not reach NetApp SVM API: {exc}",
        )

    # Allow 404 from NetApp (already deleted on server)
    if response.status_code not in (200, 204, 404):
        raise HTTPException(
            status_code=502,
            detail=f"NetApp SVM API returned {response.status_code}: {response.text}",
        )

    # 3. Synchronize local storage wipe
    delete_s3_user(db, current_user, environment, username)
    return None

@app.post("/api/s3/buckets", status_code=201, response_model=S3BucketSchema)
async def create_new_s3_bucket(
    payload: S3BucketCreate,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_required()),
):
    """
    Create a new S3 bucket on the NetApp SVM and track it locally.
    """
    # Guard against duplicate active names inside this environment natively
    active_buckets = get_s3_buckets(db, current_user, payload.environment)
    if any(b.name == payload.name for b in active_buckets):
        raise HTTPException(status_code=409, detail="Bucket tracking name already localized to this environment.")

    cfg = _get_svm_or_404(payload.environment)
    netapp_url = f"{cfg.base_url}/protocols/s3/buckets"
    
    netapp_body = {
        "name": payload.name,
        "svm": {
            "name": cfg.svm_name
        }
    }

    try:
        async with get_netapp_client(cfg, timeout=30) as client:
            response = await client.post(
                netapp_url,
                json=netapp_body,
                headers=_netapp_headers(),
            )
    except httpx.RequestError as exc:
        raise HTTPException(status_code=502, detail=f"Could not reach NetApp SVM API: {exc}")

    if response.status_code not in (200, 201, 202):
        raise HTTPException(status_code=502, detail=f"NetApp SVM API returned {response.status_code}: {response.text}")

    # Fire background Generation for IAM Policies natively bridging this Bucket
    try:
        async with get_netapp_client(cfg, timeout=30) as client:
            full_access_payload = {
                "name": f"FullAccess_{payload.name}",
                "statements": [{
                    "effect": "allow",
                    "actions": ["*"],
                    "resources": [payload.name, f"{payload.name}/*"]
                }]
            }
            read_only_payload = {
                "name": f"ReadOnly_{payload.name}",
                "statements": [{
                    "effect": "allow",
                    "actions": ["GetObject", "ListBucket"],
                    "resources": [payload.name, f"{payload.name}/*"]
                }]
            }
            policy_url = f"{cfg.base_url}/protocols/s3/services/{cfg.svm_uuid}/policies"
            # We don't block the frontend heavily if these fail, but we'll try natively hooking them
            await client.post(policy_url, json=full_access_payload, headers=_netapp_headers())
            await client.post(policy_url, json=read_only_payload, headers=_netapp_headers())
    except Exception as e:
        print(f"Failed generating Policies automatically behind the scenes for bucket {payload.name}: {e}")

    # Immediately lock async representation into database proxy
    db_bucket = create_s3_bucket(db, current_user, payload.environment, payload.name)
    return db_bucket


@app.get("/api/s3/buckets", response_model=S3BucketListResponse)
async def list_s3_buckets(
    environment: str,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_required()),
):
    """
    Fetch S3 buckets for the environment, explicitly resolving pending async creations and trailing deletions natively.
    """
    cfg = _get_svm_or_404(environment)
    db_buckets = get_s3_buckets(db, current_user, environment)

    pending_creations = [b for b in db_buckets if b.bucket_uuid == "pending"]
    pending_deletions = [b for b in db_buckets if b.deletion == "pending"]
    
    if pending_creations or pending_deletions:
        try:
            async with get_netapp_client(cfg, timeout=30) as client:
                response = await client.get(f"{cfg.base_url}/protocols/s3/buckets", headers=_netapp_headers())
                if response.status_code == 200:
                    data = response.json()
                    netapp_records = data.get("records", [])
                    
                    active_environment_buckets = [
                        r for r in netapp_records 
                        if r.get("svm", {}).get("name", "") == cfg.svm_name
                    ]
                    active_uuids = {r.get("uuid") for r in active_environment_buckets}
                    
                    # Resolve Pending Creations
                    for p in pending_creations:
                        match = next((r for r in active_environment_buckets if r.get("name") == p.name), None)
                        if match:
                            update_s3_bucket_uuid(db, p.id, match.get("uuid"))
                            p.bucket_uuid = match.get("uuid")
                            
                    # Resolve Pending Deletions
                    for p in pending_deletions:
                        if p.bucket_uuid not in active_uuids:
                            timestamp = datetime.utcnow().isoformat()
                            mark_s3_bucket_deleted(db, p.id, timestamp)
                            p.deletion = timestamp

        except Exception as e:
            print(f"Bucket Async Resolution Failed: {str(e)}")

    # Filter out heavily timestamped buckets representing completed background deletes natively from the array
    filtered_buckets = [b for b in db_buckets if b.deletion in (None, "pending")]
    return S3BucketListResponse(data=filtered_buckets)


@app.get("/api/s3/buckets/{bucket_uuid}")
async def get_s3_bucket_details(
    bucket_uuid: str,
    environment: str = Query(...),
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_required()),
):
    """
    Fetch comprehensive raw JSON configuration details for a given bucket UUID from NetApp.
    """
    if bucket_uuid == "pending":
        raise HTTPException(status_code=400, detail="Cannot fetch details for a pending UUID bucket.")

    # 1. Enforce local environment boundaries
    db_buckets = get_s3_buckets(db, current_user, environment)
    target_bucket = next((b for b in db_buckets if b.bucket_uuid == bucket_uuid), None)
    if not target_bucket:
        raise HTTPException(status_code=404, detail="Bucket tracking not found or you lack ownership permissions.")

    cfg = _get_svm_or_404(environment)
    netapp_url = f"{cfg.base_url}/protocols/s3/buckets/{cfg.svm_uuid}/{bucket_uuid}"

    try:
        async with get_netapp_client(cfg, timeout=30) as client:
            response = await client.get(netapp_url, headers=_netapp_headers())
    except httpx.RequestError as exc:
        raise HTTPException(status_code=502, detail=f"Could not reach NetApp SVM API: {exc}")

    if response.status_code not in (200,):
        raise HTTPException(status_code=502, detail=f"NetApp SVM API returned {response.status_code}: {response.text}")

    return response.json()


class ObjectAccessUpdate(BaseModel):
    username: str
    access: str # "none", "read", "full"

@app.get("/api/s3/buckets/{bucket_uuid}/access")
async def get_bucket_access(
    bucket_uuid: str,
    environment: str = Query(...),
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_required()),
):
    target_bucket = db.query(S3Bucket).filter(S3Bucket.bucket_uuid == bucket_uuid, S3Bucket.owner_email == current_user, S3Bucket.environment == environment).first()
    if not target_bucket: raise HTTPException(status_code=404, detail="Bucket not found.")

    all_users = get_s3_users(db, current_user, environment)
    cfg = _get_svm_or_404(environment)
    
    full_users = []
    read_users = []
    
    try:
        async with get_netapp_client(cfg, timeout=30) as client:
            res = await client.get(f"{cfg.base_url}/protocols/s3/services/{cfg.svm_uuid}/groups?fields=**&return_records=true", headers=_netapp_headers())
            if res.status_code == 200:
                for grp in res.json().get("records", []):
                    if grp.get("name") == f"GrpFullAccess_{target_bucket.name}":
                        full_users = [u.get("name") for u in grp.get("users", [])]
                    elif grp.get("name") == f"GrpReadOnly_{target_bucket.name}":
                        read_users = [u.get("name") for u in grp.get("users", [])]
    except Exception as e:
        print(f"Failed pulling groups dynamically: {e}")
        
    res_list = []
    for u in all_users:
        act = "none"
        if u.username in full_users: act = "full"
        elif u.username in read_users: act = "read"
        res_list.append({"username": u.username, "access": act})
        
    return {"access_list": res_list}


@app.put("/api/s3/buckets/{bucket_uuid}/access")
async def update_bucket_access(
    bucket_uuid: str,
    payload: List[ObjectAccessUpdate],
    environment: str = Query(...),
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_required()),
):
    target_bucket = db.query(S3Bucket).filter(S3Bucket.bucket_uuid == bucket_uuid, S3Bucket.owner_email == current_user, S3Bucket.environment == environment).first()
    if not target_bucket: raise HTTPException(status_code=404, detail="Bucket not found.")
    cfg = _get_svm_or_404(environment)
    
    desired_full = [{"name": p.username} for p in payload if p.access == "full"]
    desired_read = [{"name": p.username} for p in payload if p.access == "read"]
    
    async def manage_dynamic_group(grp_name, policy_name, desired_users, client):
        group_url = f"{cfg.base_url}/protocols/s3/services/{cfg.svm_uuid}/groups"
        
        # 1. Sweep active
        active_id = None
        current_users = []
        res = await client.get(f"{group_url}?name={grp_name}&fields=**&return_records=true", headers=_netapp_headers())
        if res.status_code == 200 and res.json().get("records"):
            active_id = res.json()["records"][0].get("id")
            current_users = res.json()["records"][0].get("users", [])
            
        # 2. Logic loop
        if not desired_users:
            if active_id:
                await client.delete(f"{group_url}/{active_id}", headers=_netapp_headers())
        else:
            if not active_id:
                await client.post(group_url, json={"name": grp_name, "policies": [{"name": policy_name}], "users": desired_users}, headers=_netapp_headers())
            else:
                await client.patch(f"{group_url}/{active_id}", json={"users": desired_users}, headers=_netapp_headers())

    try:
        async with get_netapp_client(cfg, timeout=30) as client:
            await manage_dynamic_group(f"GrpFullAccess_{target_bucket.name}", f"FullAccess_{target_bucket.name}", desired_full, client)
            await manage_dynamic_group(f"GrpReadOnly_{target_bucket.name}", f"ReadOnly_{target_bucket.name}", desired_read, client)
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Failed updating dynamically scaled proxies natively: {e}")
        
    return {"message": "Access successfully pushed"}
    
@app.delete("/api/s3/buckets/{bucket_uuid}", status_code=204)
async def delete_s3_bucket_route(
    bucket_uuid: str,
    environment: str = Query(...),
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_required()),
):
    """
    Delete an S3 bucket off NetApp targeting its active UUID string.
    """
    if bucket_uuid == "pending":
        raise HTTPException(
            status_code=400, 
            detail="Cannot delete a bucket that is actively resolving its UUID. Please refresh the grid."
        )

    # 1. Enforce local environment boundaries
    db_buckets = get_s3_buckets(db, current_user, environment)
    target_bucket = next((b for b in db_buckets if b.bucket_uuid == bucket_uuid), None)
    if not target_bucket:
        raise HTTPException(status_code=404, detail="Bucket tracking not found or you lack ownership permissions.")

    if target_bucket.deletion == "pending":
        raise HTTPException(status_code=400, detail="Bucket is already queued for background deletion natively.")

    cfg = _get_svm_or_404(environment)
    netapp_url = f"{cfg.base_url}/protocols/s3/buckets/{cfg.svm_uuid}/{bucket_uuid}"

    # 2. Fire the network cancellation command to SVM
    try:
        async with get_netapp_client(cfg, timeout=30) as client:
            # 2a: Scrape and physically destroy orphaned proxy Groups dynamically to allow ONTAP to drop the policies cleanly
            try:
                group_url = f"{cfg.base_url}/protocols/s3/services/{cfg.svm_uuid}/groups"
                res = await client.get(group_url, headers=_netapp_headers())
                if res.status_code == 200:
                    grps = res.json().get("records", [])
                    for g in grps:
                        gname = g.get("name", "")
                        if gname in (f"GrpFullAccess_{target_bucket.name}", f"GrpReadOnly_{target_bucket.name}"):
                            gid = g.get("id")
                            if gid:
                                await client.delete(f"{group_url}/{gid}", headers=_netapp_headers())
            except Exception as e:
                print(f"Silently failed dropping dynamic groups during bucket wipe: {e}")

            # 2b: Drop the explicitly mapped static Policies
            try:
                policy_url = f"{cfg.base_url}/protocols/s3/services/{cfg.svm_uuid}/policies"
                await client.delete(f"{policy_url}/FullAccess_{target_bucket.name}", headers=_netapp_headers())
                await client.delete(f"{policy_url}/ReadOnly_{target_bucket.name}", headers=_netapp_headers())
            except Exception as e:
                print(f"Silently failed dropping policies during bucket wipe: {e}")
                
            # 2c: Execute master Bucket payload override
            response = await client.delete(netapp_url, headers=_netapp_headers())
    except httpx.RequestError as exc:
        raise HTTPException(status_code=502, detail=f"Could not reach NetApp SVM API: {exc}")

    # NetApp physically blocked deletion, likely because the bucket still actively houses file objects!
    if response.status_code == 400:
        raise HTTPException(
            status_code=400,
            detail="NetApp blocked bucket deletion! Ensure the bucket is entirely empty of objects before deleting."
        )
        
    if response.status_code not in (200, 204, 404, 202):
        raise HTTPException(status_code=502, detail=f"NetApp SVM API returned {response.status_code}: {response.text}")

    # 3. Synchronize local storage to a pending deletion sweep state
    mark_s3_bucket_deleting(db, current_user, environment, bucket_uuid)
    return None


@app.get("/api/health")
async def health_check():
    """Health check endpoint"""
    return {
        "status": "healthy",
        "auth_enabled": settings.enable_entra_auth,
        "version": "1.0.0"
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)